name: 🐞 Bug report (When self-deploying)
description: Report an issue or possible bug when deploy to your own server or cloud.
labels: ['pending triage', 'deploy']
body:
  - type: markdown
    attributes:
      value: |
        ### Before submitting...
        Thanks for taking the time to fill out this bug report! Please confirm the following points before submitting:

        ✅ I am using **latest version of GeminiProChat**. 
        ✅ I have checked the bug was not already reported by searching on GitHub under issues.
        ✅ Use English to ask questions. This allows more people to search and participate in the issue.
  - type: dropdown
    id: server
    attributes:
      label: How is Gemini Pro Chat deployed?
      description: Select the used deployment method.
      options:
        - Node
        - Docker
        - Vercel
        - Netlify
        - Railway
        - Others (Specify in description)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Please check your browser and node console, fill in the error message if it exists.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false